import { Creator, Series } from './types';

export const featuredCreators: Creator[] = [
  { id: 1, name: 'Shanmukh Jaswanth', handle: '@shanmukh_jaswanth', imageUrl: 'https://picsum.photos/seed/shanmukh/200/200', bio: 'Storyteller, actor, and director known for creating compelling Telugu web series that resonate with the youth.', socials: { youtube: '#', instagram: '#', twitter: '#' } },
  { id: 2, name: 'Deepthi Sunaina', handle: '@deepthi_sunaina', imageUrl: 'https://picsum.photos/seed/deepthi/200/200', bio: 'A popular digital creator and actress who brings charm and emotion to her short films and performances.', socials: { youtube: '#', instagram: '#', twitter: '#' } },
  { id: 3, name: 'Bhuvan Bam', handle: '@bhuvan.bam22', imageUrl: 'https://picsum.photos/seed/bhuvan/200/200', bio: 'One of India\'s biggest digital superstars, creating hilarious and relatable characters that have won millions of hearts.', socials: { youtube: '#', instagram: '#', twitter: '#' } },
  { id: 4, name: 'Prajakta Koli', handle: '@mostlysane', imageUrl: 'https://picsum.photos/seed/prajakta/200/200', bio: 'An actress and creator whose content spans comedy, lifestyle, and social commentary, known for her authenticity.', socials: { youtube: '#', instagram: '#', twitter: '#' } },
  { id: 5, name: 'Alekhya Harika', handle: '@alekhya_harika', imageUrl: 'https://picsum.photos/seed/alekhya/200/200', bio: 'Famous for her "Dhethadi" series, she captures the essence of Telangana culture with her unique brand of comedy.', socials: { youtube: '#', instagram: '#', twitter: '#' } },
  { id: 6, name: 'Ashish Chanchlani', handle: '@ashishchanchlani', imageUrl: 'https://picsum.photos/seed/ashish/200/200', bio: 'A powerhouse of comedy, creating viral sketches and videos that are packed with energy and laughter.', socials: { youtube: '#', instagram: '#', twitter: '#' } },
  { id: 7, name: 'Tharun Bhascker', handle: '@tharunbhascker', imageUrl: 'https://picsum.photos/seed/tharun/200/200', bio: 'A National Award-winning director and writer, bringing a fresh, modern perspective to Telugu cinema.', socials: { youtube: '#', instagram: '#', twitter: '#' } },
  { id: 8, name: 'Kusha Kapila', handle: '@kushakapila', imageUrl: 'https://picsum.photos/seed/kusha/200/200', bio: 'An actress and comedian known for her sharp wit and hilarious takes on pop culture and everyday life.', socials: { youtube: '#', instagram: '#', twitter: '#' } },
];

export const trendingSeries: Series[] = [
  { 
    id: 1, 
    title: 'Software Developer', 
    creator: 'Shanmukh Jaswanth', 
    genre: 'Telugu Web Series', 
    imageUrl: 'https://picsum.photos/seed/series1/1920/1080',
    synopsis: 'A gripping tale of a young programmer navigating the high-stakes world of a tech startup in Hyderabad. He faces challenges, rivalries, and a moral dilemma that could change his life forever.',
    cast: ['Shanmukh Jaswanth', 'Vaishnavi Chaitanya', 'Prithvi Mukka'],
    episodes: [
      { id: 1, title: 'The First Line of Code', duration: '5:12' },
      { id: 2, title: 'The Bug', duration: '4:45' },
      { id: 3, title: 'The Deadline', duration: '6:02' },
    ],
    featured: true,
    averageRating: 4.8,
    ratingCount: 2400,
  },
  { 
    id: 2, 
    title: 'Malgudi Days', 
    creator: 'Deepthi Sunaina', 
    genre: 'Short Film', 
    imageUrl: 'https://picsum.photos/seed/series2/800/1200',
    synopsis: 'A nostalgic journey back to a simpler time, this series of short stories captures the essence of life in a small South Indian town, filled with charm, wit, and heartwarming moments.',
    cast: ['Deepthi Sunaina', 'Ravi Teja', 'Ananya Sharma'],
    episodes: [
        { id: 1, title: 'The Swami', duration: '7:30' },
        { id: 2, title: 'The Postman', duration: '6:55' },
    ],
    averageRating: 4.5,
    ratingCount: 980,
  },
  { 
    id: 3, 
    title: 'Dhindora', 
    creator: 'Bhuvan Bam', 
    genre: 'Comedy', 
    imageUrl: 'https://picsum.photos/seed/series3/800/1200',
    synopsis: 'When an unexpected lottery win turns their lives upside down, one man and his family must navigate a hilarious series of chaotic events. A laugh-out-loud entertainer.',
    cast: ['Bhuvan Bam', 'Gayatri Bhardwaj', 'Jeevan Raut'],
    episodes: [
        { id: 1, title: 'Lag Gayi', duration: '4:15' },
        { id: 2, title: 'The Masterplan', duration: '5:05' },
        { id: 3, title: 'Baazi', duration: '5:40' },
        { id: 4, title: 'Sasta Sherlock', duration: '6:10' },
    ],
    averageRating: 4.9,
    ratingCount: 5100,
  },
  { 
    id: 4, 
    title: 'Khayali Pulao', 
    creator: 'Prajakta Koli', 
    genre: 'Short Film', 
    imageUrl: 'https://picsum.photos/seed/series4/800/1200',
    synopsis: 'A small-town girl dreams of making it to the school handball team, not for the love of the game, but for a chance to wear shorts. A heartwarming story about ambition and freedom.',
    cast: ['Prajakta Koli', 'Yashpal Sharma', 'Geeta Sharma'],
    episodes: [
        { id: 1, title: 'The Dream', duration: '8:00' },
    ],
    averageRating: 4.6,
    ratingCount: 1200,
  },
  { 
    id: 5, 
    title: 'Dhethadi', 
    creator: 'Alekhya Harika', 
    genre: 'Telugu Comedy', 
    imageUrl: 'https://picsum.photos/seed/series5/800/1200',
    synopsis: 'Follow the hilarious antics of a bold and unapologetic girl from Telangana as she tackles everyday situations with her unique brand of humor and wit.',
    cast: ['Alekhya Harika', 'Rahul Ramakrishna'],
    episodes: [
        { id: 1, title: 'The Arranged Marriage', duration: '4:50' },
        { id: 2, title: 'The Exam Stress', duration: '5:22' },
        { id: 3, title: 'The Nosy Neighbor', duration: '4:30' },
    ],
    averageRating: 4.7,
    ratingCount: 1800,
  },
  { 
    id: 6, 
    title: 'ACV Hatke', 
    creator: 'Ashish Chanchlani', 
    genre: 'Sketch', 
    imageUrl: 'https://picsum.photos/seed/series6/800/1200',
    synopsis: 'A collection of ridiculously relatable and over-the-top comedy sketches that poke fun at everything from student life to Bollywood movies. Expect non-stop laughter.',
    cast: ['Ashish Chanchlani', 'Kunal Chhabhria', 'Simran Dhanwani'],
    episodes: [
        { id: 1, title: 'Tuition Classes', duration: '6:18' },
        { id: 2, title: 'The Sasta Bi-gg Boss', duration: '7:04' },
    ],
    averageRating: 4.4,
    ratingCount: 2100,
  },
  { 
    id: 7, 
    title: 'Behind Ee Nagaraniki Emaindi', 
    creator: 'Tharun Bhascker', 
    genre: 'Featurette', 
    imageUrl: 'https://picsum.photos/seed/series7/800/1200',
    synopsis: 'Go behind the scenes of the iconic film. This featurette explores the making of the movie, with exclusive interviews, deleted scenes, and bloopers.',
    cast: ['Tharun Bhascker', 'Vishwak Sen', 'Sushanth Reddy'],
    episodes: [
        { id: 1, title: 'The Making Of', duration: '9:45' },
    ],
    averageRating: 4.3,
    ratingCount: 500,
  },
  { 
    id: 8, 
    title: 'Behensplaining', 
    creator: 'Kusha Kapila', 
    genre: 'Review Show', 
    imageUrl: 'https://picsum.photos/seed/series8/800/1200',
    synopsis: 'Two best friends hilariously review and roast the latest movies and web shows, offering their unfiltered and witty commentary. No filter, all fun.',
    cast: ['Kusha Kapila', 'Srishti Dixit'],
    episodes: [
        { id: 1, title: 'The One With The Bad Remake', duration: '5:30' },
        { id: 2, title: 'The One With The Epic Finale', duration: '6:12' },
    ],
    averageRating: 4.6,
    ratingCount: 850,
  },
];